version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: magic-rules-db
    restart: unless-stopped
    ports:
      - '5432:5432' # host:container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
